[project]
name = "fl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "numpy",
  "pandas>=3.0.0",
  "requests>=2.32.5",
  "scikit-learn>=1.8.0",
  "torch",
  "torchvision",
]

[project.optional-dependencies]
dev = [
  "basedpyright>=1.37.3",
  "black>=25.12.0",
  "ipykernel>=7.1.0",
  "matplotlib>=3.10.8",
]

[tool.basedpyright]
typeCheckingMode = "standard"

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://mirrors.seu.edu.cn/pytorch/whl/cu130/simple"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }
torchvision = { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" }
